sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_script:
  - docker build -t op01/ssl .
script:
  - standard
  - docker run --privileged --entrypoint /bin/sh op01/ssl -c "cd /app; npm test"
notifications:
  email: false
